services:
    app:
        build:
            context: .
            target: development
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - PORT=3000
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - redis
        command: yarn dev:local

    redis:
        image: redis:7-alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        command: redis-server --appendonly yes

volumes:
    redis_data:
